name: Run E2E Tests

on: [pull_request]

jobs:
  run-unit-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          - POSTGRES_USERNAME: docker
          - POSTGRES_PASSWORD: docker
          - POSTGRES_DATABASE: gympassapi

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"

      - run: npm ci

      - run: npm run test:e2e
