name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"

      - run: npm ci

      - run: npm run test
